name: Build

on: [ push ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2
        
      - name: Setup JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 11
                
      - name: Run KtLint Formatter
        run: ./ktlintFormat
                
      - name: Build with Gradle
        run: ./gradlew build
